// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearScreen() {
  return window['go']['main']['App']['ClearScreen']();
}

export function ToggleMode() {
  return window['go']['main']['App']['ToggleMode']();
}
